<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Flowspan.Application/Flowspan.Application.csproj" />
    <ProjectReference Include="../../src/Flowspan.Domain/Flowspan.Domain.csproj" />
    <ProjectReference Include="../../src/Flowspan.Protocol/Flowspan.Protocol.csproj" />
    <ProjectReference Include="../../src/Flowspan.Security/Flowspan.Security.csproj" />
    <ProjectReference Include="../../src/Flowspan.Transport/Flowspan.Transport.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Fixtures/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
