<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Windows platform adapters for Flowspan.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Flowspan.Security/Flowspan.Security.csproj" />
  </ItemGroup>
</Project>
