<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Flowspan.Domain/Flowspan.Domain.csproj" />
    <ProjectReference Include="../../src/Flowspan.Platform/Flowspan.Platform.csproj" />
    <ProjectReference Include="../../src/Flowspan.Platform.MacOS/Flowspan.Platform.MacOS.csproj" />
    <ProjectReference Include="../../src/Flowspan.Security/Flowspan.Security.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
