<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>macOS platform adapters for Flowspan.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Flowspan.Security/Flowspan.Security.csproj" />
  </ItemGroup>
</Project>
